### ISSUE TITLE
Support for [Manor Lords]

### ISSUE THREAD

**Issue by TheAkeno** [Z1ni/XGP-save-extractor#154] opened 2024-05-06 09:44 UTC

**Comment by TheAkeno** [comment] 2024-05-06 09:45
Game package name: HoodedHorse.ManorLords_znaey1dw2bdpr

**Comment by DeicPro** [comment] 2024-05-06 18:51
Duplicate of https://github.com/Z1ni/XGP-save-extractor/issues/152

**Comment by Z1ni** [comment] 2024-07-03 13:48
Closed as duplicate of #152

**Closed by Z1ni** 2024-07-03 13:48 UTC
Labels: new game support

**Comment by Z1ni** [comment] 2024-07-04 23:35
Support for Manor Lords is now available: https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-07-05
