### ISSUE TITLE
From Steam to Xbox

### ISSUE THREAD

**Issue by ArcLeRetourr** [Z1ni/XGP-save-extractor#111] opened 2024-01-31 21:32 UTC
Hi, i'm just here to ask you if there is any way you can create something that make steam file to xbox file please ? (for palworld atleast)

Have a nice day

**Comment by Z1ni** [comment] 2024-01-31 22:14
Duplicate of #101 

Check out https://github.com/HarukaMa/palworld-xgp-import

**Closed by Z1ni** 2024-01-31 22:14 UTC
Labels: new game support
