### ISSUE TITLE
Support for Persona 3 Reload (please)

### ISSUE THREAD

**Issue by minteahna** [Z1ni/XGP-save-extractor#116] opened 2024-02-02 08:15 UTC
## Game package name: SEGAofAmericaInc.L0cb6b3aea_s751p9cej88mt

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/14137138/wgs.zip)

Steam Save File Location: AppData/Roaming/SEGA/P3R/Steam
[76561199018685231.zip](https://github.com/Z1ni/XGP-save-extractor/files/14137172/76561199018685231.zip)

**Comment by Z1ni** [comment] 2024-02-02 09:09
Duplicate of #114.
Please follow that issue.

Thanks for the saves, they'll help!

**Closed by Z1ni** 2024-02-02 09:09 UTC
Labels: new game support
