### ISSUE TITLE
Palworld

### ISSUE THREAD

**Issue by BlossomCam** [Z1ni/XGP-save-extractor#89] opened 2024-01-20 03:26 UTC
## Game name: 
can you have it so it works with Palworld?

**Comment by Z1ni** [comment] 2024-01-20 18:38
Duplicate of #88.
Palworld support has been added to the newest release, https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-01-20.

**Closed by Z1ni** 2024-01-20 18:38 UTC
Labels: new game support
