### ISSUE TITLE
Support for Gotham Knights

### ISSUE THREAD

**Issue by sonicnerd14** [Z1ni/XGP-save-extractor#95] opened 2024-01-21 01:59 UTC
## Game package name: WarnerBros.Interactive.ea2bab08-46b7-40e4-bdd5-590_ktmk1xygcecda
[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/13999718/wgs.zip)

**Comment by Z1ni** [comment] 2024-01-24 20:06
Duplicate of #50

**Closed by Z1ni** 2024-01-24 20:06 UTC
Labels: new game support
