### ISSUE TITLE
Extractor fail issue - Starfield

### ISSUE THREAD

**Issue by Dsheppp** [Z1ni/XGP-save-extractor#112] opened 2024-01-31 23:20 UTC
Installed supported games:
- Starfield
  Failed to extract saves:
Traceback (most recent call last):
  File "\\VBoxSvr\Share\main.py", line 492, in main
  File "\\VBoxSvr\Share\main.py", line 344, in get_save_paths
ValueError: invalid literal for int() with base 10: 'BlobData0'

any help would be appreciated! i can launch from game pass and it will sync and let me load old files but no luck with steam.

**Comment by Z1ni** [comment] 2024-01-31 23:30
Duplicate of #110

**Closed** 2024-01-31 23:30 UTC
Labels: new game support
