### ISSUE TITLE
Support for [PalWorld]

### ISSUE THREAD

**Issue by Jim5e** [Z1ni/XGP-save-extractor#90] opened 2024-01-20 10:36 UTC
## Game name: 
PalWorld

**Comment by Z1ni** [comment] 2024-01-20 18:38
Duplicate of #88.
Palworld support has been added to the newest release, https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-01-20.

**Closed by Z1ni** 2024-01-20 18:38 UTC
Labels: new game support
