### ISSUE TITLE
Support for [shadow of war]

### ISSUE THREAD

**Issue by Kiddeoo** [Z1ni/XGP-save-extractor#179] opened 2024-07-26 00:32 UTC
## Game name: 
shadow of war

**Comment by Kiddeoo** [comment] 2024-07-26 04:25
[wgs.zip](https://github.com/user-attachments/files/16386533/wgs.zip)

**Comment by Z1ni** [comment] 2024-07-28 15:37
Duplicate of #40

**Closed by Z1ni** 2024-07-28 15:37 UTC
Labels: new game support
