### ISSUE TITLE
Support for Monster Hunter Rise

### ISSUE THREAD

**Issue by Huntecher** [Z1ni/XGP-save-extractor#166] opened 2024-06-15 06:56 UTC
## Game package name: F024294D.50755C2F12831_8fty0by30jkny

[wgs.zip](https://github.com/user-attachments/files/15846127/wgs.zip)

**Comment by Z1ni** [comment] 2024-07-03 13:59
Duplicate of #86

**Closed by Z1ni** 2024-07-03 13:59 UTC
Labels: new game support

**Comment by Z1ni** [comment] 2024-07-03 14:39
I tried to extract your saves, can you confirm if those work?

[monster_hunter_rise_2535467671905894_2024-07-03_17_34_32.zip](https://github.com/user-attachments/files/16086520/monster_hunter_rise_2535467671905894_2024-07-03_17_34_32.zip)
