### ISSUE TITLE
Support for Gotham Knights

### ISSUE THREAD

**Issue by Rumik** [Z1ni/XGP-save-extractor#54] opened 2023-10-19 10:43 UTC
Game name: Gotham Knights
Game package name: WarnerBros.Interactive.ea2bab08-46b7-40e4-bdd5-590_ktmk1xygcecda

https://1drv.ms/u/s!Asi1zUxsGE36pOAm-F2TePTyHZJyYg?e=uQ32aR

**Comment by Z1ni** [comment] 2024-01-24 20:06
Duplicate of #50

**Closed by Z1ni** 2024-01-24 20:06 UTC
Labels: new game support
