### ISSUE TITLE
Support for Middle-Earth: Shadow Of War

### ISSUE THREAD

**Issue by tizerheads** [Z1ni/XGP-save-extractor#64] opened 2023-11-12 22:09 UTC
## Game package name: WarnerBros.Interactive.WB-Kraken_ktmk1xygcecda

WGS Zipped Gamesave Link: [https://1drv.ms/u/s!Ai6iR3p1I4UKlZYVLrN44ASlYn_j2w?e=bLtNiC]

**Comment by Luilem** [comment] 2024-01-14 07:59
Hi! Any news about this?

**Comment by tizerheads** [comment] 2024-01-14 08:00
None I’m afraid 😟

—This email was sent from my mobile device.—

**Comment by Z1ni** [comment] 2024-01-25 17:37
Duplicate of #40

**Closed by Z1ni** 2024-01-25 17:37 UTC
Labels: new game support
