### ISSUE TITLE
Support for Cassette beasts

### ISSUE THREAD

**Issue by IlovePokemon2000** [Z1ni/XGP-save-extractor#140] opened 2024-03-19 17:58 UTC

**Comment by Z1ni** [comment] 2024-07-03 17:36
From the issue template:
> Game saves from the Xbox Game Pass / Microsoft Store version are needed to add support for the game.
> Here's how to obtain the saves:
> 1. Open up the Windows Run dialog by pressing Win+R
> 2. Type in "%LOCALAPPDATA%\Packages" (without quotes)
> 3. Search for a folder name that possibly includes the name of the game or the name of the game developer or publisher. The name format should be something like "DeveloperOrPublisherName.PossibleGameName_RandomLettersAndNumbers", e.g. "BethesdaSoftworks.ProjectGold_3275kfvn8vcwc" for Starfield.
> 
> If you found a suitable folder name:
> 4. Copy and paste the folder name below in this text field. That's the package name for the game.
> 5. Open up the folder and the "SystemAppData" folder inside it.
> 6. Zip up the "wgs" folder.

**Comment by Z1ni** [comment] 2024-07-03 17:41
Duplicate of #56

**Closed by Z1ni** 2024-07-03 17:41 UTC
Labels: new game support, need more details
