### ISSUE TITLE
add Middle earth shadow of war save please

### ISSUE THREAD

**Issue by AdamDB92** [Z1ni/XGP-save-extractor#174] opened 2024-07-15 20:40 UTC
## Game name: Middle earth shadow of war

 I got the steam version
[356190.zip](https://github.com/user-attachments/files/16240094/356190.zip)

## Game package name: WarnerBros.Interactive.WB-Kraken_ktmk1xygcecda
[wgs.zip](https://github.com/user-attachments/files/16240095/wgs.zip)

**Comment by Z1ni** [comment] 2024-07-28 15:37
Duplicate of #40

**Closed by Z1ni** 2024-07-28 15:37 UTC
Labels: new game support
