### ISSUE TITLE
Support for Persona 3 Reload

### ISSUE THREAD

**Issue by dr1055** [Z1ni/XGP-save-extractor#115] opened 2024-02-02 06:16 UTC
## Game package name: SEGAofAmericaInc.L0cb6b3aea_s751p9cej88mt

[wgs.zip](https://github.com/Z1ni/XGP-save-extractor/files/14135834/wgs.zip)
[SteamSave.zip](https://github.com/Z1ni/XGP-save-extractor/files/14135844/SteamSave.zip)

**Comment by Z1ni** [comment] 2024-02-02 09:08
Duplicate of #114.
Please follow that issue.

Also thanks for the saves, they'll help!

**Closed by Z1ni** 2024-02-02 09:08 UTC
Labels: new game support
