### ISSUE TITLE
Failed to create save game error and how I'm trying to "

### ISSUE THREAD

**Issue by EuphoniousNonsense** [Z1ni/XGP-save-extractor#17] opened 2023-09-10 04:06 UTC
I posted this to reddit as well but I think this is a better place to maybe get help.  My goal here is just simply recover my last save file, which does still load fine and works without issue but i cannot save due to the error/bug, and then convert to steam friendly save file so I can stop using the Xbox Game Pass version and use the steam version instead.

**_REDDIT POST 1_**

Been fighting this after getting to lvl 17 last night. When i booted game today getting this error. Tried everything listed here. I decided the best course of action was the converter from xbox game pass to steam and I would just buy the game there HOWEVER when I try to run the python script i get an error. The strange part is if I revert this file
C:\Users\*myusername*\AppData\Local\Packages\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\SystemAppData\wgs\00090000039FB06A_0000000000000000000000007BF72399\containers.index
back to the default that I saved a backup of before playing (thanks bethesda, this is a trait your games created in me) it will run just the script fine not when using the file my game has created over the course of playing it. I cannot code nor do I have the patience to teach myself it to figure this issue out. Anyone got any ideas?
Here is the error
C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06>python main.py

Xbox Game Pass for PC savefile extractor

========================================

Installed supported games:

- Starfield

Failed to extract saves:

Traceback (most recent call last):

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 255, in main

read_result = read_containers(supported_xgp_apps[name])

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 102, in read_containers

with open(os.path.join(container_path, f"container.{container_num}"), "rb") as cf:

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*myusername*\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\00090000039FB06A_0000000000000000000000007BF72399\\6A105BD4D7F54CFB819A80B6C046C7A5\\container.2'
PLEASE NOTE - *myusername* is not my actual username just a placeholder. * are invalid for file names.

**_REDDIT POST REPLY 1_**

Tried recreating the folders it was looking for in the script with a container.2 file in each but we get to the end and now i am getting this error I cannot seem to solve.
C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06>python main.py

Xbox Game Pass for PC savefile extractor

========================================

Installed supported games:

- Starfield

Failed to extract saves:

Traceback (most recent call last):

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 263, in main

save_paths = get_save_paths(store_pkg_name, containers, temp_dir)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\*myusername*\Desktop\XGP-save-extractor-release-2023-09-06\main.py", line 220, in get_save_paths

with open(part_path, "rb") as part_f:

^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*myusername*\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\00090000039FB06A_0000000000000000000000007BF72399\\6A105BD4D7F54CFB819A80B6C046C7A5\\600D23C8F23D4EBBA3D9DC95152DAE2C'

**_REDDIT POST REPLY 2_**

Created a copy of container.2 and renamed it to 600D23C8F23D4EBBA3D9DC95152DAE2C and then deleted the file extension. This actually worked to move to next file and got me past that error.  I did the same to the next files it listed however ended up in a loop.  Stuck back at as of right now.

 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*myusername*\\AppData\\Local\\Packages\\BethesdaSoftworks.ProjectGold_3275kfvn8vcwc\\SystemAppData\\wgs\\00090000039FB06A_0000000000000000000000007BF72399\\6A105BD4D7F54CFB819A80B6C046C7A5\\600D23C8F23D4EBBA3D9DC95152DAE2C

**Comment by Z1ni** [comment] 2023-09-11 06:25
Duplicate of #18

**Closed by Z1ni** 2023-09-11 06:25 UTC
