### ISSUE TITLE
Support for Palworld

### ISSUE THREAD

**Issue by Daniel-USA** [Z1ni/XGP-save-extractor#92] opened 2024-01-20 16:06 UTC
## Palworld: 

<!--
PocketpairInc.Palworld_ad4psfrxyesvt

https://www.dropbox.com/scl/fi/3qrezm440hqmulwuga8wd/wgs.zip?rlkey=uugkoq44ad0rgq1eoy58gwp2k&dl=0

**Comment by Z1ni** [comment] 2024-01-20 18:38
Duplicate of #88.
Palworld support has been added to the newest release, https://github.com/Z1ni/XGP-save-extractor/releases/tag/release-2024-01-20.

**Closed by Z1ni** 2024-01-20 18:38 UTC
Labels: new game support
